# Generated by Django 5.0 on 2024-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_category_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('UX Design', 'UX Design'), ('Development', 'Development'), ('Production', 'Production')], max_length=255),
        ),
    ]
