# Generated by Django 5.0 on 2024-07-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], max_length=20),
        ),
    ]
